config/routes.rb
Rails.application.routes.draw do
  get 'units/index'
  get 'units/import'
  post 'units/parse'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def import
  end

  def parse
    format = params[:format]
    Etl::ParserOrganizer.call(format)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtlStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/units/import.html.erb
<h1>Units#trigger</h1>
<%= link_to 'List', units_index_path %>

<%= form_tag('/units/parse', method: 'post') do %>
  <%= label_tag(:q, 'Format:') %>
  <%= radio_button_tag(:format, 'csv') %>
  <%= label_tag(:format_csv, 'CSV') %>
  <%= radio_button_tag(:format, 'json') %>
  <%= label_tag(:format_json, 'JSON') %>
  <%= submit_tag('Import') %>
<% end %>

app/views/units/index.html.erb
<h1>Units#index</h1>

<%= link_to 'Imports', units_import_path %>

<table>
  <th>
    <td>
      id
    </td>
  </th>
  <th>
    <td>
      name
    </td>
  </th>
  <th>
    <td>
      description
    </td>
  </th>
  <th>
    <td>
      price
    </td>
  </th>

  <% @units.each do |unit| %>
  <tr>
    <td><%= unit.id %></td>
    <td><%= unit.name %></td>
    <td><%= unit.description %></td>
    <td><%= unit.price %></td>
  </tr>
  <% end %>
</table>